### ISSUE TITLE
Подтверждение отправки в заданиях 5-7

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/you_can_bot#101]
### Сейчас
В заданиях 5, 6 и 7 пользователь вводит ответ в сообщении, а не нажимает кнопки. Есть проблема, которая заключается в том, что пользователь подумает, что ответить нужно в нескольких сообщениях. Что приводит к такой ситуации:

<img height="75%" src="https://lh3.googleusercontent.com/drive-viewer/AK7aPaCymU6kvK3OfaiBC1B0veG8WCCyaQxLqJ703dnETtcQyObV-yJe8sHvGsw-5mA_XAgtN6vtPFZLtSsKf6b8QBZDamTDLw=w1872-h956">

### Нужно
В ходе обсуждений с заказчиком было решено добавить подтверждение отправки ответа, как это сделано при обработке команды /ask, когда пользователь отправляет свой вопрос.

Дополнительно к этому нужно добавить отслеживание редактирования сообщения, чтобы работала следующая логика
1.  Пользователь вводит сообщение
2. Бот спрашивает подтверждение
3. Пользователь редактирует сообщение, которое отправил раннее 
4. Пользователь нажимает "Подтвердить"
4. Бот сохраняет _отредактированный_ текст

Думаю, что для перехвата редактирования сообщения можно использовать этот фильтр https://docs.python-telegram-bot.org/en/stable/telegram.ext.filters.html#telegram.ext.filters.UpdateType.EDITED_MESSAGE

**Comment by DmitrySmolov** [comment]
Не уверен, что я до конца понял...
На примере с /ask, если я правильно понял, нужно оповестить пользователя, что он может подтвердить или отменить сохранение своего последнего сообщения, а также исправить его? Так?
И теперь в добавок к старой механике, на случай если вдруг пользователь исправил своё сообщение и только после этого нажал на "подтвердить", нам нужно сначала проверить, не изменилось ли его сообщение, и только после этого сохранить его в неизменённой или изменённой форме? Так?

![Image](https://github.com/Studio-Yandex-Practicum/you_can_bot/assets/115971796/1ce4ab82-e104-4fdb-94b2-926d728ea117)
![Image](https://github.com/Studio-Yandex-Practicum/you_can_bot/assets/115971796/b8a657b0-2e6a-4708-a6e6-7b690289dad4)

**Comment by TomatoInOil** [comment]
Да, верно 
Но ещё нужно добавить такое подтверждение в Задания с развёрнутым ответом (задания 5, 6 и 7)
